"""add indexes on foreign key columns

Revision ID: 195b5efa1803
Revises: e0250a8c497e
Create Date: 2026-09-10 00:02:21.510319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195b5efa1803'
down_revision: Union[str, None] = 'e0250a8c497e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dictation_attempts_dictation_session_id'), 'dictation_attempts', ['dictation_session_id'], unique=False)
    op.create_index(op.f('ix_dictation_attempts_sentence_id'), 'dictation_attempts', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_dictation_sessions_text_id'), 'dictation_sessions', ['text_id'], unique=False)
    op.create_index(op.f('ix_dictation_sessions_user_id'), 'dictation_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_recall_attempts_recall_session_id'), 'recall_attempts', ['recall_session_id'], unique=False)
    op.create_index(op.f('ix_recall_attempts_sentence_id'), 'recall_attempts', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_recall_sessions_text_id'), 'recall_sessions', ['text_id'], unique=False)
    op.create_index(op.f('ix_recall_sessions_user_id'), 'recall_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sentence_translation_links_english_sentence_id'), 'sentence_translation_links', ['english_sentence_id'], unique=False)
    op.create_index(op.f('ix_sentence_translation_links_translation_sentence_id'), 'sentence_translation_links', ['translation_sentence_id'], unique=False)
    op.create_index(op.f('ix_sentences_chunk_id'), 'sentences', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_text_chunks_text_id'), 'text_chunks', ['text_id'], unique=False)
    op.create_index(op.f('ix_texts_user_id'), 'texts', ['user_id'], unique=False)
    op.create_index(op.f('ix_translation_sentences_text_id'), 'translation_sentences', ['text_id'], unique=False)
    op.create_index(op.f('ix_typing_errors_sentence_id'), 'typing_errors', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_typing_errors_session_id'), 'typing_errors', ['session_id'], unique=False)
    op.create_index(op.f('ix_typing_sessions_chunk_id'), 'typing_sessions', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_typing_sessions_text_id'), 'typing_sessions', ['text_id'], unique=False)
    op.create_index(op.f('ix_typing_sessions_user_id'), 'typing_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_typing_sessions_user_id'), table_name='typing_sessions')
    op.drop_index(op.f('ix_typing_sessions_text_id'), table_name='typing_sessions')
    op.drop_index(op.f('ix_typing_sessions_chunk_id'), table_name='typing_sessions')
    op.drop_index(op.f('ix_typing_errors_session_id'), table_name='typing_errors')
    op.drop_index(op.f('ix_typing_errors_sentence_id'), table_name='typing_errors')
    op.drop_index(op.f('ix_translation_sentences_text_id'), table_name='translation_sentences')
    op.drop_index(op.f('ix_texts_user_id'), table_name='texts')
    op.drop_index(op.f('ix_text_chunks_text_id'), table_name='text_chunks')
    op.drop_index(op.f('ix_sentences_chunk_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentence_translation_links_translation_sentence_id'), table_name='sentence_translation_links')
    op.drop_index(op.f('ix_sentence_translation_links_english_sentence_id'), table_name='sentence_translation_links')
    op.drop_index(op.f('ix_recall_sessions_user_id'), table_name='recall_sessions')
    op.drop_index(op.f('ix_recall_sessions_text_id'), table_name='recall_sessions')
    op.drop_index(op.f('ix_recall_attempts_sentence_id'), table_name='recall_attempts')
    op.drop_index(op.f('ix_recall_attempts_recall_session_id'), table_name='recall_attempts')
    op.drop_index(op.f('ix_dictation_sessions_user_id'), table_name='dictation_sessions')
    op.drop_index(op.f('ix_dictation_sessions_text_id'), table_name='dictation_sessions')
    op.drop_index(op.f('ix_dictation_attempts_sentence_id'), table_name='dictation_attempts')
    op.drop_index(op.f('ix_dictation_attempts_dictation_session_id'), table_name='dictation_attempts')
    # ### end Alembic commands ###
