"""recall sessions and attempts

Revision ID: 5f6c9c0bb699
Revises: f0a4e12b2888
Create Date: 2026-09-09 12:08:19.485878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6c9c0bb699'
down_revision: Union[str, None] = 'f0a4e12b2888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recall_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recall_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recall_session_id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('typed', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('correct_words', sa.Integer(), nullable=False),
    sa.Column('incorrect_words', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recall_session_id'], ['recall_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recall_attempts')
    op.drop_table('recall_sessions')
    # ### end Alembic commands ###
