"""translation alignment and dictionary

Revision ID: 84183997e7d8
Revises: 1d1ddb98b22d
Create Date: 2026-09-09 09:21:34.781839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84183997e7d8'
down_revision: Union[str, None] = '1d1ddb98b22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headword', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('translations', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dictionary_entries_headword', 'dictionary_entries', ['headword'], unique=False)
    op.create_table('translation_sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_translation_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('english_sentence_id', sa.UUID(), nullable=False),
    sa.Column('translation_sentence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['english_sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translation_sentence_id'], ['translation_sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('texts', sa.Column('translation_content', sa.Text(), nullable=True))
    op.add_column(
        'texts',
        sa.Column('alignment_status', sa.String(length=20), nullable=False, server_default='not_provided'),
    )
    op.alter_column('texts', 'alignment_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'alignment_status')
    op.drop_column('texts', 'translation_content')
    op.drop_table('sentence_translation_links')
    op.drop_table('translation_sentences')
    op.drop_index('ix_dictionary_entries_headword', table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    # ### end Alembic commands ###
