"""preserve session history on text deletion (SET NULL not CASCADE)

Revision ID: 87783de64709
Revises: d85540341f67
Create Date: 2026-09-10 04:39:21.851688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87783de64709'
down_revision: Union[str, None] = 'd85540341f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dictation_attempts', 'sentence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('dictation_attempts_sentence_id_fkey', 'dictation_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'dictation_attempts', 'sentences', ['sentence_id'], ['id'], ondelete='SET NULL')
    op.alter_column('dictation_sessions', 'text_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('dictation_sessions_text_id_fkey', 'dictation_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'dictation_sessions', 'texts', ['text_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recall_attempts', 'sentence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('recall_attempts_sentence_id_fkey', 'recall_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'recall_attempts', 'sentences', ['sentence_id'], ['id'], ondelete='SET NULL')
    op.alter_column('recall_sessions', 'text_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('recall_sessions_text_id_fkey', 'recall_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'recall_sessions', 'texts', ['text_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('typing_sessions_chunk_id_fkey', 'typing_sessions', type_='foreignkey')
    op.drop_constraint('typing_sessions_text_id_fkey', 'typing_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'typing_sessions', 'texts', ['text_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'typing_sessions', 'text_chunks', ['chunk_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'typing_sessions', type_='foreignkey')
    op.drop_constraint(None, 'typing_sessions', type_='foreignkey')
    op.create_foreign_key('typing_sessions_text_id_fkey', 'typing_sessions', 'texts', ['text_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('typing_sessions_chunk_id_fkey', 'typing_sessions', 'text_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'recall_sessions', type_='foreignkey')
    op.create_foreign_key('recall_sessions_text_id_fkey', 'recall_sessions', 'texts', ['text_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recall_sessions', 'text_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'recall_attempts', type_='foreignkey')
    op.create_foreign_key('recall_attempts_sentence_id_fkey', 'recall_attempts', 'sentences', ['sentence_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recall_attempts', 'sentence_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'dictation_sessions', type_='foreignkey')
    op.create_foreign_key('dictation_sessions_text_id_fkey', 'dictation_sessions', 'texts', ['text_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dictation_sessions', 'text_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'dictation_attempts', type_='foreignkey')
    op.create_foreign_key('dictation_attempts_sentence_id_fkey', 'dictation_attempts', 'sentences', ['sentence_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dictation_attempts', 'sentence_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
