"""translation modes and sentence context

Revision ID: b21aa59b9d73
Revises: 195b5efa1803
Create Date: 2026-09-10 00:45:00.562407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21aa59b9d73'
down_revision: Union[str, None] = '195b5efa1803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('translation_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('sentence_phrases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('english_phrase', sa.String(length=255), nullable=False),
    sa.Column('spanish_phrase', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_phrases_sentence_id'), 'sentence_phrases', ['sentence_id'], unique=False)
    op.add_column('sentences', sa.Column('grammar_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'grammar_note')
    op.drop_index(op.f('ix_sentence_phrases_sentence_id'), table_name='sentence_phrases')
    op.drop_table('sentence_phrases')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
