"""persist real typing session duration

Revision ID: ba19261636f4
Revises: 87783de64709
Create Date: 2026-09-10 04:56:16.482206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba19261636f4'
down_revision: Union[str, None] = '87783de64709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typing_sessions', sa.Column('duration_seconds', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typing_sessions', 'duration_seconds')
    # ### end Alembic commands ###
