"""dictation sessions attempts and audio cache

Revision ID: e0250a8c497e
Revises: 5f6c9c0bb699
Create Date: 2026-09-09 13:36:08.070614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0250a8c497e'
down_revision: Union[str, None] = '5f6c9c0bb699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictation_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dictation_session_id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('typed', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('correct_words', sa.Integer(), nullable=False),
    sa.Column('incorrect_words', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictation_session_id'], ['dictation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictation_audio_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('audio_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictation_audio_cache')
    op.drop_table('dictation_attempts')
    op.drop_table('dictation_sessions')
    # ### end Alembic commands ###
