"""move dictation audio cache to disk

Revision ID: ebfc8aa6e23b
Revises: ba19261636f4
Create Date: 2026-09-10 04:59:45.407272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebfc8aa6e23b'
down_revision: Union[str, None] = 'ba19261636f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictation_audio_cache', 'audio_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictation_audio_cache', sa.Column('audio_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
