"""vocabulary tracking and review sessions

Revision ID: f0a4e12b2888
Revises: 84183997e7d8
Create Date: 2026-09-09 11:45:01.536198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a4e12b2888'
down_revision: Union[str, None] = '84183997e7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('encounters', sa.Integer(), nullable=False),
    sa.Column('typing_errors', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_vocabulary_items_user_word')
    )
    op.add_column('typing_sessions', sa.Column('review_sentence_ids', sa.ARRAY(sa.UUID()), nullable=True))
    op.alter_column('typing_sessions', 'text_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('typing_sessions', 'chunk_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('typing_sessions', 'chunk_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('typing_sessions', 'text_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('typing_sessions', 'review_sentence_ids')
    op.drop_table('vocabulary_items')
    # ### end Alembic commands ###
